{% set name = "dexp" %}
{% set version = "2023.4.10.686" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f026db0768d50c2e254959de01982fe36f62d3c362788fc9f1512595802c0a7e

build:
  entry_points:
    - dexp=dexp.cli.dexp_main:cli
    - dexp-video=dexp.cli.video_main:cli
    - dexp-install=dexp.cli.install_main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - arbol
    - cachey
    - cairocffi
    - click >=8.0.0
    - colorcet
    - cupy
    - dask-core >=21.6.0
    - dask-cuda >=21.6.0
    - dask-image
    - distributed
    - fasteners
    - gpustat
    - gputil
    - gputools
    - imageio
    - joblib
    - numba
    - numcodecs
    - numexpr
    - numpy >=1.20
    - ome-zarr
    - platformdirs
    - pyotf
    - pytest
    - python >={{ python_min }}
    - python-blosc
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tifffile
    - toolz
    - tqdm
    - zarr

test:
  imports:
    - dexp
  commands:
    - pip list
    # - pip check
    - dexp --help
    - dexp-video --help
    - dexp-install --help
  requires:
    - oclgrind
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/royerlab/dexp
  summary: Light-sheet Dataset EXploration and Processing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - JoOkuma
